#ifndef GUARD_tilesets_H
#define GUARD_tilesets_H

extern const u32 gTilesetTiles_General[];
extern const u16 gTilesetPalettes_General[][16];

extern const struct Tileset *const gTilesetPointer_SecretBase;
extern const struct Tileset *const gTilesetPointer_SecretBaseRedCave;

extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_BuildingFrlg;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_GenericBuilding1;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_General_Frlg;
extern const struct Tileset gTileset_PalletTown;
extern const struct Tileset gTileset_ViridianCity;
extern const struct Tileset gTileset_PewterCity;
extern const struct Tileset gTileset_SaffronCity;
extern const struct Tileset gTileset_CeruleanCity;
extern const struct Tileset gTileset_LavenderTown;
extern const struct Tileset gTileset_VermilionCity;
extern const struct Tileset gTileset_CeladonCity;
extern const struct Tileset gTileset_FuchsiaCity;
extern const struct Tileset gTileset_CinnabarIsland;
extern const struct Tileset gTileset_SeviiIslands123;
extern const struct Tileset gTileset_SeviiIslands45;
extern const struct Tileset gTileset_SeviiIslands67;
extern const struct Tileset gTileset_DepartmentStore;
extern const struct Tileset gTileset_PokemonCenterFrlg;
extern const struct Tileset gTileset_SilphCo;
extern const struct Tileset gTileset_SSAnne;
extern const struct Tileset gTileset_SeaCottage;
extern const struct Tileset gTileset_TrainerTower;


// --- BEGIN WIRE_TO_DECOMP sinnoh ---
extern const struct Tileset gTileset_SinnohPrimary_083DF704;
extern const struct Tileset gTileset_SinnohPrimary_083DF884;
extern const struct Tileset gTileset_SinnohPrimary_083DFC5C;
extern const struct Tileset gTileset_SinnohPrimary_089CBC6C;
extern const struct Tileset gTileset_SinnohSecondary_08305DE0;
extern const struct Tileset gTileset_SinnohSecondary_083DF71C;
extern const struct Tileset gTileset_SinnohSecondary_083DF734;
extern const struct Tileset gTileset_SinnohSecondary_083DF74C;
extern const struct Tileset gTileset_SinnohSecondary_083DF764;
extern const struct Tileset gTileset_SinnohSecondary_083DF77C;
extern const struct Tileset gTileset_SinnohSecondary_083DF794;
extern const struct Tileset gTileset_SinnohSecondary_083DF7AC;
extern const struct Tileset gTileset_SinnohSecondary_083DF7C4;
extern const struct Tileset gTileset_SinnohSecondary_083DF7DC;
extern const struct Tileset gTileset_SinnohSecondary_083DF7F4;
extern const struct Tileset gTileset_SinnohSecondary_083DF80C;
extern const struct Tileset gTileset_SinnohSecondary_083DF824;
extern const struct Tileset gTileset_SinnohSecondary_083DF83C;
extern const struct Tileset gTileset_SinnohSecondary_083DF854;
extern const struct Tileset gTileset_SinnohSecondary_083DF86C;
extern const struct Tileset gTileset_SinnohSecondary_083DF89C;
extern const struct Tileset gTileset_SinnohSecondary_083DF8B4;
extern const struct Tileset gTileset_SinnohSecondary_083DF8CC;
extern const struct Tileset gTileset_SinnohSecondary_083DF8E4;
extern const struct Tileset gTileset_SinnohSecondary_083DF8FC;
extern const struct Tileset gTileset_SinnohSecondary_083DF92C;
extern const struct Tileset gTileset_SinnohSecondary_083DF944;
extern const struct Tileset gTileset_SinnohSecondary_083DF95C;
extern const struct Tileset gTileset_SinnohSecondary_083DF974;
extern const struct Tileset gTileset_SinnohSecondary_083DF98C;
extern const struct Tileset gTileset_SinnohSecondary_083DF9A4;
extern const struct Tileset gTileset_SinnohSecondary_083DF9BC;
extern const struct Tileset gTileset_SinnohSecondary_083DF9D4;
extern const struct Tileset gTileset_SinnohSecondary_083DF9EC;
extern const struct Tileset gTileset_SinnohSecondary_083DFA04;
extern const struct Tileset gTileset_SinnohSecondary_083DFA1C;
extern const struct Tileset gTileset_SinnohSecondary_083DFA34;
extern const struct Tileset gTileset_SinnohSecondary_083DFA4C;
extern const struct Tileset gTileset_SinnohSecondary_083DFA64;
extern const struct Tileset gTileset_SinnohSecondary_083DFA7C;
extern const struct Tileset gTileset_SinnohSecondary_083DFA94;
extern const struct Tileset gTileset_SinnohSecondary_083DFAC4;
extern const struct Tileset gTileset_SinnohSecondary_083DFADC;
extern const struct Tileset gTileset_SinnohSecondary_083DFAF4;
extern const struct Tileset gTileset_SinnohSecondary_083DFB0C;
extern const struct Tileset gTileset_SinnohSecondary_083DFB24;
extern const struct Tileset gTileset_SinnohSecondary_083DFB3C;
extern const struct Tileset gTileset_SinnohSecondary_083DFB54;
extern const struct Tileset gTileset_SinnohSecondary_083DFB6C;
extern const struct Tileset gTileset_SinnohSecondary_083DFB84;
extern const struct Tileset gTileset_SinnohSecondary_083DFB9C;
extern const struct Tileset gTileset_SinnohSecondary_083DFBB4;
extern const struct Tileset gTileset_SinnohSecondary_083DFBCC;
extern const struct Tileset gTileset_SinnohSecondary_083DFBE4;
extern const struct Tileset gTileset_SinnohSecondary_083DFBFC;
extern const struct Tileset gTileset_SinnohSecondary_083DFC14;
extern const struct Tileset gTileset_SinnohSecondary_083DFC2C;
extern const struct Tileset gTileset_SinnohSecondary_083DFC44;
extern const struct Tileset gTileset_SinnohSecondary_083DFC7C;
extern const struct Tileset gTileset_SinnohSecondary_083DFC94;
extern const struct Tileset gTileset_SinnohSecondary_083DFCAC;
extern const struct Tileset gTileset_SinnohSecondary_083DFCC4;
extern const struct Tileset gTileset_SinnohSecondary_083DFCDC;
extern const struct Tileset gTileset_SinnohSecondary_083DFCF4;
extern const struct Tileset gTileset_SinnohSecondary_083DFD0C;
extern const struct Tileset gTileset_SinnohSecondary_083DFD24;
extern const struct Tileset gTileset_SinnohSecondary_083DFD3C;
extern const struct Tileset gTileset_SinnohSecondary_083DFD54;
extern const struct Tileset gTileset_SinnohSecondary_083DFD6C;
extern const struct Tileset gTileset_SinnohSecondary_083DFD84;
extern const struct Tileset gTileset_SinnohSecondary_083DFD9C;
extern const struct Tileset gTileset_SinnohSecondary_083DFDB4;
extern const struct Tileset gTileset_SinnohSecondary_083DFDCC;
extern const struct Tileset gTileset_SinnohSecondary_083DFDE4;
extern const struct Tileset gTileset_SinnohSecondary_083DFDFC;
extern const struct Tileset gTileset_SinnohSecondary_089CD34C;
extern const struct Tileset gTileset_SinnohSecondary_08A5FEB4;
extern const struct Tileset gTileset_SinnohSecondary_08A62224;
extern const struct Tileset gTileset_SinnohSecondary_08A6550C;
extern const struct Tileset gTileset_SinnohSecondary_08D0190C;
// --- END WIRE_TO_DECOMP sinnoh ---

#endif //GUARD_tilesets_H
